### PR TITLE
Parse AS path regular expression

### PR DESCRIPTION
**Pull request by SichangHe**
With some limitations, implemented `Compliance::filter_as_regex`.

- Explicitly skip AS path regex with `~`.
- `as_path_regex::Interpreter`.
    - Replace ASNs and AS sets with Unicode characters starting from Α (Alpha).
    - Store the replacement logic.
    - Compile regex after replacement.
- `bgp::cmp::as_regex::AsRegex`.
    - Represent AS path as strings and match against the regex from the interpreter.
    - Record skips such as `AsSetUnrecorded` and `AsRegexPathWithSet` and report them only if the match failed.

## TODOs

- [ ] Unit Test the checking.
~~- [ ] Handle `^{m}`, `^{m,n}`, `^{m,}`~~ Not real. They don't have `^`.

### CODE REVIEW

**Comment by SichangHe** [comment]
Related: https://github.com/SichangHe/internet_route_verification/issues/35#issuecomment-1668771864

**Comment by SichangHe** [comment]
Note that I also tried walking high-level intermediate representation of regex from `regex-syntax`, but gave up after going 300 lines of code in.

**Comment by cunha** [comment]
Extreme. In our case it seems we can just match against the single-character regex, so I think we're fine. For reference given you've put in some effort:

I made traversal over the intermediate data structure in the past because I needed to check whether I could "splice" to phrases to match a regex. I remember that I needed a graph-like intermediate representation **and** the ability to map each node in the graph to a specific "place" in the regex (this was the hardest bit I remember when I did it). Without these properties I don't know how we'd go about it.

**Comment by SichangHe** [comment]
- [ ] Handle `PeerAS`.

**Comment by SichangHe** [comment]
I don't know which cases to use to test this thing.

Finding cases where the check fails is easy.

<details>
<summary>Here are some of them.</summary>

```rust
TABLE_DUMP2|1687212000|B|91.218.184.60|49788|5.44.46.0/24|49788 12552 196844 12831 197155 200088|IGP|91.218.184.60|0|0|12552:12000 12552:12700 12552:12701 12552:22000|NAG||:
    5.44.46.0/24 -> [Seq(49788), Seq(12552), Seq(196844), Seq(12831), Seq(197155), Seq(200088)]
    MehExport { from: 200088, to: 197155, items: [NoMatch(FilterAsNum(200088, NoOp)), NoMatch(RemoteAsNum(12831)), NoMatch(RemoteAsNum(15694)), Special(Uphill)] }
    MehImport { from: 200088, to: 197155, items: [NoMatch(RemoteAsNum(12831)), NoMatch(RemoteAsNum(6939)), NoMatch(RemoteAsNum(9002)), NoMatch(RemoteAsNum(6830)), NoMatch(RemoteAsNum(24724)), Special(Uphill)] }
    MehExport { from: 197155, to: 12831, items: [NoMatch(FilterAsSet("AS-ARTNET", NoOp)), NoMatch(RemoteAsNum(6939)), NoMatch(RemoteAsNum(9002)), NoMatch(RemoteAsNum(6830)), NoMatch(RemoteAsNum(24724)), Special(Uphill)] }
    MehImport { from: 197155, to: 12831, items: [NoMatch(RemoteAsNum(5550)), NoMatch(RemoteAsNum(13293)), NoMatch(RemoteAsNum(35628)), NoMatch(RemoteAsNum(196844)), NoMatch(RemoteAsNum(12827)), NoMatch(RemoteAsNum(31683)), NoMatch(RemoteAsNum(197680)), Special(Uphill)] }
    OkExport { from: 12831, to: 196844 }
    MehImport { from: 12831, to: 196844, items: [NoMatch(RemoteAsSet("AS-AMS-IX-PEERS")), …, NoMatch(RegexMismatch("AS196844:AS-TASK-COM$")), NoMatch(RemoteAsNum(35686)), NoMatch(RemoteAsNum(15851)), NoMatch(RemoteAsNum(13065)), Special(Uphill)] }
    BadExport { from: 196844, to: 12552, items: […] }
    BadImport { from: 196844, to: 12552, items: […] }
    SkipExport { from: 12552, to: 49788, items: […] }
    OkImport { from: 12552, to: 49788 }.


TABLE_DUMP2|1687212037|B|198.129.33.85|293|217.173.205.0/24|293 196844 25584|IGP|198.129.33.85|0|7944||NAG||:
    217.173.205.0/24 -> [Seq(293), Seq(196844), Seq(25584)]
    MehExport { from: 25584, to: 196844, items: […] }
    MehImport { from: 25584, to: 196844, items: [NoMatch(RemoteAsSet("AS-AMS-IX-PEERS")), …, NoMatch(RegexMismatch("AS196844:AS-Opole-COM$")), …, Special(Uphill)] }
    BadExport { from: 196844, to: 293, items: […] }
    SkipImport { from: 196844, to: 293, items: [Skip(ImportEmpty)] }.

TABLE_DUMP2|1687212033|B|208.51.134.255|3549|202.1.166.0/24|3549 3356 4637 139609 139609 139609 45891|IGP|208.51.134.255|0|0|3356:3 3356:22 3356:86 3356:575 3356:666 3356:901 3356:2003 3549:2018 3549:30840|NAG||:
    202.1.166.0/24 -> [Seq(3549), Seq(3356), Seq(4637), Seq(139609), Seq(45891)]
    OkExport { from: 45891, to: 139609 }
    OkImport { from: 45891, to: 139609 }
    MehExport { from: 139609, to: 4637, items: [Special(ExportCustomers), NoMatch(RemoteAsNum(58941)), NoMatch(RemoteAsNum(7606))] }
    MehImport { from: 139609, to: 4637, items: [NoMatch(RemoteAsSet("AS-REACH-NAP")), NoMatch(RegexMismatch("^AS-REACH-CUSTOMERS*$")), NoMatch(RemoteAsSet("AS-REACH-PEERS")), Special(Uphill)] }
    OkExport { from: 4637, to: 3356 }
    MehImport { from: 4637, to: 3356, items: […] }
    BadExport { from: 3356, to: 3549, items: […] }
    SkipImport { from: 3356, to: 3549, items: [Skip(AutNumUnrecorded(3549))] }.

TABLE_DUMP2|1687212033|B|12.0.1.63|7018|202.1.167.0/24|7018 1299 4637 4637 4637 4637 139609 139609 139609 45891|IGP|12.0.1.63|0|0|7018:5000 7018:37232|NAG||:
    202.1.167.0/24 -> [Seq(7018), Seq(1299), Seq(4637), Seq(139609), Seq(45891)]
    OkExport { from: 45891, to: 139609 }
    OkImport { from: 45891, to: 139609 }
    MehExport { from: 139609, to: 4637, items: [Special(ExportCustomers), NoMatch(RemoteAsNum(58941)), NoMatch(RemoteAsNum(7606))] }
    MehImport { from: 139609, to: 4637, items: [NoMatch(RemoteAsSet("AS-REACH-NAP")), NoMatch(RegexMismatch("^AS-REACH-CUSTOMERS*$")), NoMatch(RemoteAsSet("AS-REACH-PEERS")), Special(Uphill)] }
    MehExport { from: 4637, to: 1299, items: [NoMatch(RemoteAsSet("AS-REACH-CUSTOMERS")), NoMatch(RemoteAsSet("AS-REACH-NAP")), NoMatch(RemoteAsSet("AS-REACH-PEERS")), Special(UphillTier1)] }
    OkImport { from: 4637, to: 1299 }
    SkipExport { from: 1299, to: 7018, items: [Skip(AsSetUnrecorded("AS1299:AS-TWELVE99-CUSTOMER-V4")), Skip(AsSetUnrecorded("AS1299:AS-TWELVE99-PEER-V4"))] }
    SkipImport { from: 1299, to: 7018, items: [Skip(AutNumUnrecorded(7018))] }.
```

</details>

Finding cases where the check succeeds on regex is trickier. I suppose I should compare the reports generated with this feature on against previous reports that contains regex skips.

**Comment by SichangHe** [comment]
No unit test, yet. I think we merge this in for now and think about testing later.

**Pull request merged**
