### PR TITLE
Artifacts

### PR DESCRIPTION
**Pull request by SichangHe**
My current plan is to:

- Provide an `ARTIFACT.md` file that contains all the steps to reproduce each artifact mentioned in the text.
- Download source data from GitHub Release, though state where they are from.
- Set up Python environments automatically using Rye.
- Run some of the tasks in the shells, same as how they were done for the text, by providing the copy pasta.
- State which scripts generated the intermediate results (mainly various CSV files), but still download the results from GitHub.

The reason I start with a more manual approach to reproduce the artifacts, is that I find it clearer. If I write a giant script that does everything and spit out the results one by one, it is hard to understand what the script is doing and how the results translate (and the script can be a nightmare to maintain and debug).

What do you think, @cunha?

### CODE REVIEW

**Comment by cunha** [comment]
This plan makes sense. I just think we might want to integrate the contribution with the repository whenever possible. Ideally, the artifact would be the repo itself. This would make it easier for us to maintain and for people to use.

I agree that making steps explicit and documenting them helps.

I can *champagne* going through the steps after you have a draft and provide feedback.

**Comment by SichangHe** [comment]
> I just think we might want to integrate the contribution with the repository whenever possible. Ideally, the artifact would be the repo itself.

Well, everything I recorded is in the repository. Most things can be reproduced just by checking out the issues and linked commits, but I found some scripts to be missing, probably because I did them one-off.

P.S. Putting this off a bit. I got an infection.

**Comment by SichangHe** [comment]
I am mostly done here, @cunha, please have a look.

Five TODOs left (in `ARTIFACTS.md`); the troublesome ones being:

- [ ] Script to count sizes in Table 1 for each IRR (missing).
- [ ] Script to compute the percentage of AS pairs with single status in
    imports/exports (probably wrong).
- [ ] Counting the supported non-standard syntax usages.

Are those worth the effort?

Also, if we rerun everything again, we would probably have slight differences in the numbers (I keep the current difference I get in FIXMEs). Do we want to generate stats for a newer version of the data instead?

**Comment by SichangHe** [comment]
Added source data downloading script.

**Comment by SichangHe** [comment]
@cunha, how do we want to proceed with this now?

**Comment by cunha** [comment]
Sorry for the delay, I'll have another look at it.

**Pull request merged**
